"""Initial migration

Revision ID: ca43f8adcac2
Revises: 
Create Date: 2025-08-07 12:27:45.502405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca43f8adcac2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crafting_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('output_item', sa.String(length=50), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=True),
    sa.Column('gold_cost', sa.Integer(), nullable=True),
    sa.Column('wood_cost', sa.Integer(), nullable=True),
    sa.Column('stone_cost', sa.Integer(), nullable=True),
    sa.Column('food_cost', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('supply', sa.Integer(), nullable=True),
    sa.Column('demand', sa.Integer(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('reward_gold', sa.Integer(), nullable=True),
    sa.Column('reward_exp', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['market_items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('market')
    op.drop_table('monsters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('health', sa.INTEGER(), nullable=True),
    sa.Column('strength', sa.INTEGER(), nullable=True),
    sa.Column('armor', sa.INTEGER(), nullable=True),
    sa.Column('gold_reward', sa.INTEGER(), nullable=True),
    sa.Column('exp_reward', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('base_price', sa.INTEGER(), nullable=True),
    sa.Column('supply', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.drop_table('transactions')
    op.drop_table('daily_quests')
    op.drop_table('market_items')
    op.drop_table('crafting_recipes')
    # ### end Alembic commands ###
